Decision Tree Implementation
For Iris dataset your task is to print steps for every split in the decision tree.
Your Project is divided in 2 parts -
1. Print the Decision tree steps as specified in the example below. This is of 80 marks in total.
2. Decision Tree Implementation:  Building actual decision tree for the dataset and then printing it. This is of 20 marks.
Note: You can submit multiple times before deadline/evaluation. Your final submission will be evaluated. No submission is allowed after the project is evaluated by TA.
Dataset: Iris dataset.
Implementation: Consider the decision tree for OR below:
Alt text

Expected Output:
Level  0
Count of  0(False)  =  1
Count of  1(True)  =  3
Current Entropy  is =  0.811278124459
Splitting on feature  X1  with gain ratio  0.311278124459

Level  1
Count of  0  =  1
Count of  1  =  1
Current Entropy is =  1.0
Splitting on feature  X2  with gain ratio  1.0

Level  2
Count of  0  =  1
Current Entropy  is =  0.0
Reached leaf Node

Level  2
Count of  1  =  1
Current Entropy  is =  0.0
Reached leaf Node

Level  1
Count of  1  =  2
Current Entropy  is =  0.0
Reached leaf Node

In [127]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split

#### 01. Decision Tree on Iris DataSet Using SkLearn

In [229]:
iris = datasets.load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=1)

In [129]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [130]:
y_train_pred = clf.predict(x_train)
y_test_pred = clf.predict(x_test)

In [131]:
from sklearn.metrics import confusion_matrix

In [132]:
confusion_matrix(y_train,y_train_pred)

array([[37,  0,  0],
       [ 0, 34,  0],
       [ 0,  0, 41]], dtype=int64)

In [133]:
confusion_matrix(y_test,y_test_pred)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [134]:
import pydotplus
dot_data = export_graphviz(clf, out_file=None,feature_names=iris.feature_names,class_names=iris.target_names)
graph = pydotplus.graph_from_dot_data(dot_data)

In [135]:
graph.write_pdf('iris.pdf')

True

#### 02. Decision Tree Implementation on Iris Dataset

In [136]:
x_train

array([[6.5, 2.8, 4.6, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3. , 5.5, 2.1],
       [5.1, 3.5, 1.4, 0.3],
       [6. , 2.2, 5. , 1.5],
       [6.3, 2.9, 5.6, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [7.7, 2.6, 6.9, 2.3],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [6.9, 3.1, 5.4, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 3.4, 4.5, 1.6],
       [7.7, 2.8, 6.7, 2. ],
       [5.7, 3. , 4.2, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3. , 1.4, 0.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.5, 3. , 5.8, 2.2],
       [4.6, 3.4, 1.4, 0.3],
       [6.1, 3. , 4.9, 1.8],
       [6.5, 3.2, 5.1, 2. ],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 2.8, 4.5, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 3

In [137]:
df = pd.DataFrame(x_train)

In [138]:
df.columns = ['sep_len','sep_wid','pet_len','pet_wid']

In [141]:
df

sep_len sep_wid pet_len pet_wid
0      High     Low    High    High
1      High     Low    High    High
2      High     Low    High    High
3       Low    High     Low     Low
4      High     Low    High    High
..      ...     ...     ...     ...
107    High     Low    High    High
108    High    High    High    High
109    High     Low    High    High
110    High    High    High    High
111     Low    High     Low     Low

[112 rows x 4 columns]

In [140]:
# converting continuous values to discreet values
# For simplicity, assuming just two values discreet values for each feature 
# Low --> Less than Mean of Data
# High --> Greater than Mean of Data
# Same can be used for test data set as well

def discretize(value,*mean_val):

    # if any value is less than mean value, call it Low
    # else call it High

    if value <= mean_val[0]:
        return 'Low'
    else:
        return 'High'
        
sep_len_mean = df['sep_len'].mean()
df['sep_len'] = df['sep_len'].apply(discretize, args= [sep_len_mean])
sep_wid_mean = df['sep_wid'].mean()
df['sep_wid'] = df['sep_wid'].apply(discretize, args= [sep_wid_mean])
pet_len_mean = df['pet_len'].mean()
df['pet_len'] = df['pet_len'].apply(discretize, args= [pet_len_mean])
pet_wid_mean = df['pet_wid'].mean()
df['pet_wid'] = df['pet_wid'].apply(discretize, args= [pet_wid_mean])

In [142]:
arr = df.to_numpy()    # our input array to the build tree function

In [227]:
def entropy(labels):             # gives entropy prior to splitting

    unique, counts = np.unique(labels, return_counts=True)

    total = counts.sum(axis=0)
    counts = (counts/total)
    logs = np.log2(counts)
    counts = -1*counts

    return np.dot(counts,logs)


# classes : 
# 0 : Setosa
# 1 : Versicolor
# 2 : Virginica



def build_decision_tree(x_train,y_train,level,features):


    if len(set(y_train)) == 1 or (len(x_train[0])==1): # base case : either all values correspont to a single class or no features left to split on

        print('Level',level)
        print('This is a leaf node')
        v,c = np.unique(y_train,return_counts=True)
        
        for label,freq in zip(v,c):
            print('Count of',label,'=',freq)


        return

    ent = entropy(y_train)       # entropy before split

    info_gain = float('-inf')
    index = None   
    for i in range(len(x_train[0])):      # loop over all features, pick one which gives maximum information gain

        values,counts = np.unique(x_train[:,i],return_counts=True)

        total = counts.sum(axis=0)
        counts = counts/total          # weights for each of the split on a feature

        split_entropies = list()       

        for unique_val in values:

            v,c = np.unique(y_train[x_train[:,i]==unique_val],return_counts=True)
            tot = c.sum(axis=0)
            c = c/tot
            logs = np.log2(c)
            c = -1*c
            split_entropies.append(np.dot(c,logs))

        split_entropies = np.array(split_entropies)
        weighted_entropy = np.dot(counts,split_entropies)
        gain = ent - weighted_entropy

        if gain > info_gain:
            info_gain = gain
            index = i
    

    print('Level',level)
    y_labels,y_counts = np.unique(y_train,return_counts=True)
    for label,freq in zip(y_labels,y_counts):
        print('Count of',label,'=',freq)
    
    print('Current Entropy is:',ent)

    print('splitting on feature',features[index],'with info gain of',info_gain)
    temp = np.delete(features,index,0)              # remove the feature_name after split


    values = np.unique(x_train[:,index])
    new_train = np.delete(x_train,index,1)          # remove feature from dataset after split

    
    for split_point in values:

        bool = (x_train[:,index]==split_point)

        build_decision_tree(new_train[bool],y_train[bool],level+1,temp)

In [230]:
build_decision_tree(arr,y_train,0,np.array(['sep_len','sep_wid','pet_len','pet_wid']))

Level 0
Count of 0 = 37
Count of 1 = 34
Count of 2 = 41
Current Entropy is: 1.58071971384221
splitting on feature pet_len with info gain of 0.7566799599999647
Level 1
Count of 1 = 28
Count of 2 = 41
Current Entropy is: 0.9742408334889758
splitting on feature pet_wid with info gain of 0.10035035781727619
Level 2
Count of 1 = 23
Count of 2 = 41
Current Entropy is: 0.9421631690835511
splitting on feature sep_len with info gain of 0.011101059100075528
Level 3
This is a leaf node
Count of 1 = 18
Count of 2 = 36
Level 3
This is a leaf node
Count of 1 = 5
Count of 2 = 5
Level 2
This is a leaf node
Count of 1 = 5
Level 1
Count of 0 = 37
Count of 1 = 6
Current Entropy is: 0.5830194167347008
splitting on feature sep_wid with info gain of 0.2622474654677352
Level 2
This is a leaf node
Count of 0 = 29
Level 2
Count of 0 = 8
Count of 1 = 6
Current Entropy is: 0.9852281360342515
splitting on feature pet_wid with info gain of 0.09265128879158102
Level 3
This is a leaf node
Count of 1 = 1
Level 3
This

#### 03. Decision Tree for "OR" Operation Classification

In [244]:
# sklearn decision tree does not support categorical variables yet
# 0 : False
# 1 : True


train_data = {"X1" : ["1","0","1","0"],
          "X2" : ["1","1","0","0"]
}

train_labels = {"Y": ["1","1","1","0"]}

df_train = pd.DataFrame(train_data)
df_train_labels = pd.DataFrame(train_labels)

In [245]:
df_train

X1 X2
0  1  1
1  0  1
2  1  0
3  0  0

In [246]:
df_train_labels

Y
0  1
1  1
2  1
3  0

In [247]:
X_train = df_train.to_numpy()
y_train = df_train_labels.to_numpy()

In [248]:
X_train

array([['1', '1'],
       ['0', '1'],
       ['1', '0'],
       ['0', '0']], dtype=object)

In [249]:
y_train

array([['1'],
       ['1'],
       ['1'],
       ['0']], dtype=object)

In [250]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
import pydotplus
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [251]:
clf = DecisionTreeClassifier()

In [252]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [253]:
dot_data = export_graphviz(clf, out_file=None,feature_names=["X1","X2"],class_names=["True","False"])
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf("OR.pdf")

True